name: Initial Setup
description: checkout, install node & dependencies

inputs:
  node_version:
    description: Node version to install
    default: 18.X
    required: false

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        # cache: npm

    - name: Install Dependencies
      shell: bash
      run: npm -v
      # run: npm ci --prefer-offline
