name: Initial Setup
description: checkout, install node & dependencies

inputs:
  node_version:
    description: Node version to install
    default: 18.X

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node_version: ${{ node_version }}
        cache: npm

    - name: Install Dependencies
      shell: bash
      run: npm ci --prefer-offline
