name: Reuse

on: [workflow_call, workflow_dispatch]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: ./.github/workflows/generic-action.yml

      - run: echo "works"
